# Generated by Django 5.2 on 2025-04-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='teste',
            field=models.CharField(blank=True),
        ),
    ]
