# Generated by Django 5.2 on 2025-04-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='teste',
        ),
    ]
